// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	GetServerOperation                OperationName = "GetServer"
	ListMultiplayerSummariesOperation OperationName = "ListMultiplayerSummaries"
	ListServerStatisticsOperation     OperationName = "ListServerStatistics"
	ListServerSummariesOperation      OperationName = "ListServerSummaries"
)
