// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetMultiplayersSummary implements getMultiplayersSummary operation.
	//
	// Get multiplayers summary.
	//
	// GET /multiplayers/summary
	GetMultiplayersSummary(ctx context.Context, params GetMultiplayersSummaryParams) ([]GetMultiplayersSummaryOKItem, error)
	// GetServerByID implements getServerByID operation.
	//
	// Get server by ID.
	//
	// GET /multiplayer/{multiplayerName}/server/{serverID}
	GetServerByID(ctx context.Context, params GetServerByIDParams) (GetServerByIDRes, error)
	// GetServerStatsByID implements getServerStatsByID operation.
	//
	// Get server stats by ID.
	//
	// GET /multiplayer/{multiplayerName}/server/{serverID}/stats
	GetServerStatsByID(ctx context.Context, params GetServerStatsByIDParams) (GetServerStatsByIDRes, error)
	// GetServersByMultiplayer implements getServersByMultiplayer operation.
	//
	// Get servers by multiplayer.
	//
	// GET /multiplayer/{multiplayerName}/servers
	GetServersByMultiplayer(ctx context.Context, params GetServersByMultiplayerParams) (GetServersByMultiplayerRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
