// Code generated by ogen, DO NOT EDIT.
package api

type GetServerRes interface {
	getServerRes()
}

type ListServerStatisticsRes interface {
	listServerStatisticsRes()
}

type ListServerSummariesRes interface {
	listServerSummariesRes()
}
