// Code generated by ogen, DO NOT EDIT.

package api

import (
	"github.com/go-faster/errors"
)

func (s ListServerStatisticsOKApplicationJSON) Validate() error {
	alias := ([]ServerStatisticPoint)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}

func (s ListServerStatisticsPrecision) Validate() error {
	switch s {
	case "perHour":
		return nil
	case "perDay":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s ListServerSummariesOKApplicationJSON) Validate() error {
	alias := ([]ServerSummary)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
