// Code generated by ogen, DO NOT EDIT.
package api

type GetServerByIDRes interface {
	getServerByIDRes()
}

type GetServerStatsByIDRes interface {
	getServerStatsByIDRes()
}

type GetServersByMultiplayerRes interface {
	getServersByMultiplayerRes()
}
