// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetMultiplayersSummary implements getMultiplayersSummary operation.
//
// Get multiplayers summary.
//
// GET /multiplayers/summary
func (UnimplementedHandler) GetMultiplayersSummary(ctx context.Context, params GetMultiplayersSummaryParams) (r []GetMultiplayersSummaryOKItem, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServerByID implements getServerByID operation.
//
// Get server by ID.
//
// GET /multiplayer/{multiplayerName}/server/{serverID}
func (UnimplementedHandler) GetServerByID(ctx context.Context, params GetServerByIDParams) (r GetServerByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServerStatsByID implements getServerStatsByID operation.
//
// Get server stats by ID.
//
// GET /multiplayer/{multiplayerName}/server/{serverID}/stats
func (UnimplementedHandler) GetServerStatsByID(ctx context.Context, params GetServerStatsByIDParams) (r GetServerStatsByIDRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetServersByMultiplayer implements getServersByMultiplayer operation.
//
// Get servers by multiplayer.
//
// GET /multiplayer/{multiplayerName}/servers
func (UnimplementedHandler) GetServersByMultiplayer(ctx context.Context, params GetServersByMultiplayerParams) (r GetServersByMultiplayerRes, _ error) {
	return r, ht.ErrNotImplemented
}
