openapi: 3.0.2
info:
  version: 1.0.0
  title: Gdatum API
  description: A service for querying information about servers from different multiplayer games.
servers:
  - url: 127.0.0.1:8080
    description: Local development
tags:
  - name: monitoring
    description: Game server monitoring
paths:
  /multiplayers/summaries:
    get:
      tags:
        - monitoring
      summary: Get a summary of multiplayer platforms
      operationId: listMultiplayerSummaries
      parameters:
        - name: playersOrderAsc
          in: query
          description: Sort order by current players count
          schema:
           type: boolean
      responses:
        '200':
          $ref: "responses.yml#/components/responses/ListMultiplayerSummariesOK"
  '/multiplayer/{multiplayerName}/servers':
    get:
      tags:
        - monitoring
      summary: List servers for a multiplayer platform
      operationId: listServerSummaries
      parameters:
        - name: multiplayerName
          in: path
          description: Multiplayer platform name
          required: true
          schema:
            type: string
        - name: playersOrderAsc
          in: query
          description: Sort order by players count
          schema:
            type: boolean
        - name: limit
          in: query
          description: Maximum number of items to return in the response. Used for pagination.
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 100
        - name: offset
          in: query
          description: Number of servers to skip before starting to collect the result set. Used for pagination.
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 100
        - name: includeOffline
          in: query
          description: Whether to include offline servers
          schema:
            type: boolean
      responses:
        '200':
          $ref: "responses.yml#/components/responses/ListServerSummariesOK"
        '404':
          description: Multiplayer not found
  '/multiplayer/{multiplayerName}/server/{serverHost}':
    get:
      tags:
        - monitoring
      summary: Get server by host
      operationId: getServer
      parameters:
        - name: multiplayerName
          in: path
          description: Multiplayer platform name
          required: true
          schema:
            type: string
        - name: serverHost
          in: path
          description: Server host
          required: true
          schema:
            type: string
      responses:
        '200':
          $ref: "responses.yml#/components/responses/GetServerOK"
        '404':
          description: Server not found
  '/multiplayer/{multiplayerName}/server/{serverHost}/statistics':
    get:
      tags:
        - monitoring
      summary: Get server statistics by host
      operationId: listServerStatistics
      parameters:
        - name: multiplayerName
          in: path
          description: Multiplayer platform name
          required: true
          schema:
            type: string
        - name: serverHost
          in: path
          description: Server host
          required: true
          schema:
            type: string
        - name: from
          in: query
          description: Start of the time range
          required: true
          schema:
            type: string
            format: date-time
        - name: to
          in: query
          description: End of the time range
          required: true
          schema:
            type: string
            format: date-time
        - name: precision
          in: query
          description: Output precision
          schema:
            type: string
            default: perHour
            enum:
              - perHour
              - perDay
      responses:
        '200':
          $ref: "responses.yml#/components/responses/ListServerStatisticsOK"
        '404':
          description: Server not found
